### ISSUE TITLE
lightning emoji broken for some users

### ISSUE THREAD

**Issue by benthecarman** [benthecarman/zapple-pay-backend#19]

**Comment by alexgleason** [comment]
Apparently the zap emoji can have unicode modifiers like skin color. I ended up adding this function to my bridge:

```ts
function isZapEmoji(value: string): boolean {
  return  /^\u26A1[\uFE00-\uFE0F]?$/.test(value);
}
```

**Comment by benthecarman** [comment]
Thanks, added https://github.com/benthecarman/zapple-pay-backend/commit/2c3a7c253b1e0bc996a50e5f64fc589eb660c03c
