### ISSUE TITLE
Not zapping

### ISSUE THREAD

**Issue by rolznz** [benthecarman/zapple-pay-backend#2]
Hi,
I setup a new connection at https://www.zapplepay.com/, set the emoji to 🤙 and pasted in my pubkey. I setup a new NWC connection in nwc.getalby.com with a budget, but after a few likes (using Damus, so should be 🤙) my NWC connection still shows 0 sats.

Let me know if I did something wrong!

**Comment by benthecarman** [comment]
There was an issue with parsing some profiles, it should be working now.

Do note the zap will say it is from Zapple Pay, not you

**Comment by rolznz** [comment]
What is the npub field for?

**Comment by benthecarman** [comment]
> What is the npub field for?

We need to know which account to look for reactions
