### ISSUE TITLE
ZapplePay is sending invoice requests to my friends node, even though the nwc connections from

### ISSUE THREAD

**Issue by A18N15** [benthecarman/zapple-pay-backend#3]

**Comment by A18N15** [comment]
Hi, I’m having issues with my NWC. I had a few connected through mutiny wallet. A friend of mine told me yesterday that he was seeing a few failed request from me through zapplepay everytime I liked his posts. Seemed weird as the NWC connections are disabled through mutiny. But then I remembered there’s no way to disable them through ZapplePay. I even deleted the mutiny wallet but the problem persists. Would you be able to investigate and or disable all connections related to my npub please ?

heres what my friend sees on his node 


nostdress  | <nil> DBG Nostr Zap from=nostr:npub1wxl6njlcgygduct7jkgzrvyvd9fylj4pqvll6p32h59wyetm5fxqjchcan
nostdress  | <nil> DBG got lnurl request domain=zapaddress.com username=fishcake
nostdress  | <nil> DBG Comment NIP57 Comment received="From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve"
nostdress  | <nil> DBG Zap relaysTag: &[relays wss://nostr.mutinywallet.com]
nostdress  | <nil> DBG Zap relays: [wss://nostr.mutinywallet.com]
nostdress  | <nil> DBG invoice generation Description="{\"id\":\"a79fb781bdb006e490d1fbd35b446a7225291a785dcea8f1e12f7ccee6d34880\",\"pubkey\":\"71bfa9cbf84110de617e959021b08c69524fcaa1033ffd062abd0ae2657ba24c\",\"created_at\":1690160975,\"kind\":9734,\"tags\":[[\"p\",\"8fb140b4e8ddef97ce4b821d247278a1a4353362623f64021484b372f948000c\"],[\"amount\",\"127000000\"],[\"lnurl\",\"lnurl1dp68gurn8ghj77npwpskgerjv4ehxtnrdakj7tnhv4kxctttdehhwm30d3h82unvwqhkv6tndp3kz6m9kvrhys\"],[\"relays\",\"wss://nostr.mutinywallet.com\"],[\"e\",\"c6611c1d85008e00625d41c384ae6334fca5879c579661509f567687f4f83e17\"]],\"content\":\"From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve\",\"sig\":\"f6ace3930cb27750532a37c101d35ae7797f659029d9248def4e9d445af9baf2bd5c01743f2641710b997d25c59b88bac0e26a9707e6650a3701c12fca4949c3\"}" backend={"Cert":"","Host":"https://ubntlnd.local:8080","Macaroon":"0201036c6e64022f030a102f0c6d3064e780912b901f608134e9ef1201301a170a08696e766f696365731204726561641205777269746500000620c3e737a7236677ab484575149c16fb7fbbef0180d90ace980a4aeea837b0f4c2"} bolt11=lnbc1270u1pjtmn60pp5umz4hr8aqygt6e4pslsnuul4j68tjnhmqmjf80lp07nrw57y8kjqhp5x94e6a9rksf3cg8j60vdyj2qfm6xsrqzx04mu4euh392tfwca89scqzzsxqyz5vqsp5drve3hcv43jzy7mxuhpa6rr8zak53y99372vvmz8q4lvjyu565zs9qyyssqx05h7s67xc3dl7m2el7n5ry4ufclmwv3xnz7z9vf5f3fpkp42fw35wqv0kdwdr8jea6mw880nfppvk5np2hshemscw9nnfp0j348apsqvsdf2j msatoshi=127000000
nostdress  | <nil> DBG Nostr Zap from=nostr:npub1wxl6njlcgygduct7jkgzrvyvd9fylj4pqvll6p32h59wyetm5fxqjchcan
nostdress  | <nil> DBG got lnurl request domain=zapaddress.com username=fishcake
nostdress  | <nil> DBG Comment NIP57 Comment received="From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve"
nostdress  | <nil> DBG Zap relaysTag: &[relays wss://nostr.mutinywallet.com]
nostdress  | <nil> DBG Zap relays: [wss://nostr.mutinywallet.com]
nostdress  | <nil> DBG invoice generation Description="{\"id\":\"673677f83752c685f155539a0805fed7b860d0165be8bae9a48b8b5d70b9f9c3\",\"pubkey\":\"71bfa9cbf84110de617e959021b08c69524fcaa1033ffd062abd0ae2657ba24c\",\"created_at\":1690160978,\"kind\":9734,\"tags\":[[\"p\",\"8fb140b4e8ddef97ce4b821d247278a1a4353362623f64021484b372f948000c\"],[\"amount\",\"127000000\"],[\"lnurl\",\"lnurl1dp68gurn8ghj77npwpskgerjv4ehxtnrdakj7tnhv4kxctttdehhwm30d3h82unvwqhkv6tndp3kz6m9kvrhys\"],[\"relays\",\"wss://nostr.mutinywallet.com\"],[\"e\",\"cd71330e7b03a3c69d2c681b089d2494a1e1d4be6c3b35a89f30bd907040d56d\"]],\"content\":\"From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve\",\"sig\":\"7d3d861c42ac6fa6246b0221dac4e555d41641c435d60e5f0672603b2592248f9082252622bb13fcafc873f9b31dd0198c1e413eab1f5232aff6fd5b67726bfa\"}" backend={"Cert":"","Host":"https://ubntlnd.local:8080","Macaroon":"0201036c6e64022f030a102f0c6d3064e780912b901f608134e9ef1201301a170a08696e766f696365731204726561641205777269746500000620c3e737a7236677ab484575149c16fb7fbbef0180d90ace980a4aeea837b0f4c2"} bolt11=lnbc1270u1pjtmn6jpp538x67j574txuzhlyu5akzftxk83d0hek3xwrq4nzeuf027n8e67shp5hj56qtwjv22vl2qh69lyyquay309ya5fcnjlt6f978yp4zt7g83qcqzzsxqyz5vqsp5c8jn473kzfy6mwknr2rplzkzehyj66wktur0ytarhl02cygrr2gs9qyyssqujzn2pd7rwp7r9xnw940e5mmu9uqf5fycqqdgsmekh3vhlwd897zeyl9ze8gra9chy98g7ft339hn37q5re6jkdwzjjg0jzw9ruehtspd0mgw5 msatoshi=127000000
nostdress  | <nil> DBG Nostr Zap from=nostr:npub1wxl6njlcgygduct7jkgzrvyvd9fylj4pqvll6p32h59wyetm5fxqjchcan


it happenned last night every time I liked one of his notes. I went into mutiny settings and deleted the wallet which closed the channels but everytime I like my friends notes, the problem would persists. Spoke to Tony from mutiny and he says issue doesn’t seem to be on his end. 

My friend also told me it’s ZapplePay that fetches the invoice request, not mutiny

Screenshots from his node:
https://cdn.nostr.build/i/3df972dd42791a228bd931e1b0e4e5985c8573839a3b86c32a37604e7d0d450e.jpg



https://cdn.nostr.build/i/694697a396006280d2f474d0d6c89bfc46188836881be391ec6d3388266cacc1.jpg


Would it be possible to disable all ZapplePay nwc connections related to my npub ?
Thank you

**Comment by benthecarman** [comment]
Yeah, what exactly is his npub and I can delete it from the db

**Comment by benthecarman** [comment]
Deleted your npub from the database, requests shouldnt go out anymore

**Comment by A18N15** [comment]
Thank you very much for your help Ben! Lightning fast support as usual ⚡️

**Comment by A18N15** [comment]
I liked 5 more notes of my friend’s just to see if the issue is resolved. He says he still got 5 requests for invoices from me

Not sure what to do

**Comment by A18N15** [comment]
Here’s what he received

nostdress | <nil> DBG Comment NIP57 Comment received="From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve"
nostdress | <nil> DBG Zap relaysTag: &[relays wss://nostr.mutinywallet.com]
nostdress | <nil> DBG Zap relays: [wss://nostr.mutinywallet.com]
nostdress | <nil> DBG invoice generation Description="{\"id\":\"ceda1dca2e9ff1a117185ed094ed672ad7bb525d75a673f1fc21ee51de95d4d0\",\"pubkey\":\"71bfa9cbf84110de617e959021b08c69524fcaa1033ffd062abd0ae2657ba24c\",\"created_at\":1690220659,\"kind\":9734,\"tags\":[[\"p\",\"8fb140b4e8ddef97ce4b821d247278a1a4353362623f64021484b372f948000c\"],[\"amount\",\"127000000\"],[\"lnurl\",\"lnurl1dp68gurn8ghj77npwpskgerjv4ehxtnrdakj7tnhv4kxctttdehhwm30d3h82unvwqhkv6tndp3kz6m9kvrhys\"],[\"relays\",\"wss://nostr.mutinywallet.com\"],[\"e\",\"4b0c5b1b0769d7b485fa4a4e1b0257298546e710960bcf9b00cbbd1d65a842bc\"]],\"content\":\"From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve\",\"sig\":\"46a1a4e335f5fa82d3f462ea64df10606c55994325c5dbbb664bbdee1da7f34df51a9417b51cb783050e8f575e691c9b9a215b4a087e4b407a7d88ba7c8b4870\"}" backend={"Cert":"","Host":"https://ubntlnd.local:8080","Macaroon":"0201036c6e64022f030a102f0c6d3064e780912b901f608134e9ef1201301a170a08696e766f696365731204726561641205777269746500000620c3e737a7236677ab484575149c16fb7fbbef0180d90ace980a4aeea837b0f4c2"} bolt11=lnbc1270u1pjtawrnpp5nm9243rmgegtln9tv9tql5cu9uehstldgh94hz6xd5t7xy8lq2mqhp5j3emhahxfrvwqp6sczxu94edqpq2e047ev4l8k3v932cqty2jc5qcqzzsxqyz5vqsp5khwhtla4r2h2l9leamk2t5e0fkwc75hal4hw8ensjl0f6j3q5aeq9qyyssqlx25vcpdy4kgwrsssc546rtczxvwh6de9jg8tmlge47endznj3shxut2s0yxvztjxp9sx0vw4lkhg3kt3j6yslf90evpuyr03zyhm7qpvnp7f3 msatoshi=127000000
nostdress | <nil> DBG Nostr Zap from=nostr:npub1wxl6njlcgygduct7jkgzrvyvd9fylj4pqvll6p32h59wyetm5fxqjchcan
nostdress | <nil> DBG got lnurl request domain=zapaddress.com username=fishcake
nostdress | <nil> DBG Comment NIP57 Comment received="From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve"
nostdress | <nil> DBG Zap relaysTag: &[relays wss://nostr.mutinywallet.com]
nostdress | <nil> DBG Zap relays: [wss://nostr.mutinywallet.com]
nostdress | <nil> DBG invoice generation Description="{\"id\":\"b5b422f6c1529ab9bf313f425bd4633402d8bec2a4df5e5c9f77f8bc6c26df3a\",\"pubkey\":\"71bfa9cbf84110de617e959021b08c69524fcaa1033ffd062abd0ae2657ba24c\",\"created_at\":1690220661,\"kind\":9734,\"tags\":[[\"p\",\"8fb140b4e8ddef97ce4b821d247278a1a4353362623f64021484b372f948000c\"],[\"amount\",\"127000000\"],[\"lnurl\",\"lnurl1dp68gurn8ghj77npwpskgerjv4ehxtnrdakj7tnhv4kxctttdehhwm30d3h82unvwqhkv6tndp3kz6m9kvrhys\"],[\"relays\",\"wss://nostr.mutinywallet.com\"],[\"e\",\"df98db6125115c856970ff6b5c56a9da4278c047a5fc92f937c87b9122def50f\"]],\"content\":\"From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve\",\"sig\":\"15aac4d71b5b119700134a13da11e214380b35605fb37b7799024dbebc184a1584b04a28a1a6f1f0b360d211da8a990c8cf6e40125c60f8e2de5335c87e01b23\"}" backend={"Cert":"","Host":"https://ubntlnd.local:8080","Macaroon":"0201036c6e64022f030a102f0c6d3064e780912b901f608134e9ef1201301a170a08696e766f696365731204726561641205777269746500000620c3e737a7236677ab484575149c16fb7fbbef0180d90ace980a4aeea837b0f4c2"} bolt11=lnbc1270u1pjtawrkpp5h4mc57r4rysur48f7ncl2hrjxdlw9dhe4a88qqg9u9ecu3gq3dzqhp5m5vhuvpee37ru5r8yta4yt77zdsjtw94eck33jvg057a8tqkk7sscqzzsxqyz5vqsp5sed3muj6ac9upw9jw06ed9552cq0vpu4j7pps9tk4z3uvzyvfkzs9qyyssqam43uh0fvekmchxajpq4fdm4kpenp9rxa9ll8gcc3uw6fj63qlf49a8dlmtrcps77jvh6zkg5agapn9nduzk78q9mekpurzs5y0gvmgqrcxgwp msatoshi=127000000
nostdress | <nil> DBG Nostr Zap from=nostr:npub1wxl6njlcgygduct7jkgzrvyvd9fylj4pqvll6p32h59wyetm5fxqjchcan
nostdress | <nil> DBG got lnurl request domain=zapaddress.com username=fishcake
nostdress | <nil> DBG Comment NIP57 Comment received="From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve"
nostdress | <nil> DBG Zap relaysTag: &[relays wss://nostr.mutinywallet.com]
nostdress | <nil> DBG Zap relays: [wss://nostr.mutinywallet.com]
nostdress | <nil> DBG invoice generation Description="{\"id\":\"7064cc67a068b0a8fb751c26559fa68472c03eb71b2d6844b4acc105e6c30311\",\"pubkey\":\"71bfa9cbf84110de617e959021b08c69524fcaa1033ffd062abd0ae2657ba24c\",\"created_at\":1690220663,\"kind\":9734,\"tags\":[[\"p\",\"8fb140b4e8ddef97ce4b821d247278a1a4353362623f64021484b372f948000c\"],[\"amount\",\"127000000\"],[\"lnurl\",\"lnurl1dp68gurn8ghj77npwpskgerjv4ehxtnrdakj7tnhv4kxctttdehhwm30d3h82unvwqhkv6tndp3kz6m9kvrhys\"],[\"relays\",\"wss://nostr.mutinywallet.com\"],[\"e\",\"6fd3190c883af1554a546c278c997c824b15637154f77496920226ee01b257e8\"]],\"content\":\"From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve\",\"sig\":\"d82d061ad0497598734e56e03d16c7f03ec4398fa9d18b694ad2ec9c34f7014e4d478d0491b48d691139708029786a28a1218205eb9699da4d0a039aed310148\"}" backend={"Cert":"","Host":"https://ubntlnd.local:8080","Macaroon":"0201036c6e64022f030a102f0c6d3064e780912b901f608134e9ef1201301a170a08696e766f696365731204726561641205777269746500000620c3e737a7236677ab484575149c16fb7fbbef0180d90ace980a4aeea837b0f4c2"} bolt11=lnbc1270u1pjtawrhpp53u7d7ujc55qsqvndjkfghv2dpaw0aatkekz3p806jljae59sp4jqhp564wt8akvmn9s90vraa9h8h3ev95che256nul42f52hhjtrlkej7scqzzsxqyz5vqsp5qwymxsslvxf5hs3nclqjh5w8t7hcm9sgaspyhsg20dvnzuw0cjls9qyyssq7zzv5y34q23w2fhxyf0nyvnz9nn6nhsmq9atyk5wqzspe4al79gn0aecvuxn7xvhg7qsw76df8cc0fjkuyh2av954df7ydge94uajfcq50gqhg msatoshi=127000000
nostdress | <nil> DBG Nostr Zap from=nostr:npub1wxl6njlcgygduct7jkgzrvyvd9fylj4pqvll6p32h59wyetm5fxqjchcan
nostdress | <nil> DBG got lnurl request domain=zapaddress.com username=fishcake
nostdress | <nil> DBG got lnurl request domain=zapaddress.com username=fishcake
nostdress | <nil> DBG Comment NIP57 Comment received="From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve"
nostdress | <nil> DBG Zap relaysTag: &[relays wss://nostr.mutinywallet.com]
nostdress | <nil> DBG Zap relays: [wss://nostr.mutinywallet.com]
nostdress | <nil> DBG invoice generation Description="{\"id\":\"81454132188c0c30025120bf33c10887a90ba9627d7843af2905c6c7ad6e6d1e\",\"pubkey\":\"71bfa9cbf84110de617e959021b08c69524fcaa1033ffd062abd0ae2657ba24c\",\"created_at\":1690220671,\"kind\":9734,\"tags\":[[\"p\",\"8fb140b4e8ddef97ce4b821d247278a1a4353362623f64021484b372f948000c\"],[\"amount\",\"127000000\"],[\"lnurl\",\"lnurl1dp68gurn8ghj77npwpskgerjv4ehxtnrdakj7tnhv4kxctttdehhwm30d3h82unvwqhkv6tndp3kz6m9kvrhys\"],[\"relays\",\"wss://nostr.mutinywallet.com\"],[\"e\",\"8d106efa661e384192d8c6fd9b2cbad5847c5ac9175cf38df4398e5fc4f6f125\"]],\"content\":\"From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve\",\"sig\":\"c9cae5c76d64fb5c38e55ab9fa17c4534715075ccdced8d32c848d35dfec57578d6443da2d23e96090cef94a788afca84f5c9b17367e6bade5390d21472b9964\"}" backend={"Cert":"","Host":"https://ubntlnd.local:8080","Macaroon":"0201036c6e64022f030a102f0c6d3064e780912b901f608134e9ef1201301a170a08696e766f696365731204726561641205777269746500000620c3e737a7236677ab484575149c16fb7fbbef0180d90ace980a4aeea837b0f4c2"} bolt11=lnbc1270u1pjtawyqpp5p3609udgv3sk0sv0ng5je4gnenxptzantjeuedxhch2eamgzcznshp5m5gksxx05pq7a8stpdap5e2jd06jhgntrsfuedvdekkkp7az8dpqcqzzsxqyz5vqsp5kvvdq0dfh2zeu488ugaeyy5y9enqzcqvynygxn0gjkcl8xgalr5q9qyyssq9rzxfae009830n8np9dyyzak62s8c4tcpeqqw3xf86z203e3pqm946esrf76rr4h9wluszqw83x0cuw4yycg65c9z3eal276xyn48zgqmpy0yu msatoshi=127000000
nostdress | <nil> DBG Nostr Zap from=nostr:npub1wxl6njlcgygduct7jkgzrvyvd9fylj4pqvll6p32h59wyetm5fxqjchcan
nostdress | <nil> DBG got lnurl request domain=zapaddress.com username=fishcake
nostdress | <nil> DBG Comment NIP57 Comment received="From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve"
nostdress | <nil> DBG Zap relaysTag: &[relays wss://nostr.mutinywallet.com]
nostdress | <nil> DBG Zap relays: [wss://nostr.mutinywallet.com]
nostdress | <nil> DBG invoice generation Description="{\"id\":\"2ac92fbf352f8db3303d99ff6df0c54aabc15873e9b2c5d6096b5bca1d06cd59\",\"pubkey\":\"71bfa9cbf84110de617e959021b08c69524fcaa1033ffd062abd0ae2657ba24c\",\"created_at\":1690220673,\"kind\":9734,\"tags\":[[\"p\",\"8fb140b4e8ddef97ce4b821d247278a1a4353362623f64021484b372f948000c\"],[\"amount\",\"127000000\"],[\"lnurl\",\"lnurl1dp68gurn8ghj77npwpskgerjv4ehxtnrdakj7tnhv4kxctttdehhwm30d3h82unvwqhkv6tndp3kz6m9kvrhys\"],[\"relays\",\"wss://nostr.mutinywallet.com\"],[\"e\",\"b5bc1715dda56c75240616efad1f9eda4279167f726067308b0572f34ef02883\"]],\"content\":\"From: nostr:npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve\",\"sig\":\"311f22d8634f89721899b1465814aa7443785a943d95ffaf2c46ff9ddbbe2188919939957ba97663401126e68308c5a1a8c7096a87f700ce9d95fa2c331f7a7b\"}" backend={"Cert":"","Host":"https://ubntlnd.local:8080","Macaroon":"0201036c6e64022f030a102f0c6d3064e780912b901f608134e9ef1201301a170a08696e766f696365731204726561641205777269746500000620c3e737a7236677ab484575149c16fb7fbbef0180d90ace980a4aeea837b0f4c2"} bolt11=lnbc1270u1pjtawyzpp594jtpuuyz788y9cpst7xl22fz0m7w8cpjvsqac9w97lkj27hkqashp5wh0hxp34hemcrgssgyz4m8trs80uztgs93a27368hweqe8rrcj9scqzzsxqyz5vqsp55nc65lkmgmpf333mkjdpz9n0dd2gq8efnmlkunjjdsdxtz22x5gs9qyyssqxt9cu0lz7wz9ghvs4lmau32f6ek06l7q3tknxuymdtg3f0xqnmhjpemh6jwgg8nljvtj9lmj5mugs8yku4qjpav4lka4vty3z48hmtqp54qtvs msatoshi=127000000
nostdress | <nil> DBG Nostr Zap from=nostr:npub1wxl6njlcgygduct7jkgzrvyvd9fylj4pqvll6p32h59wyetm5fxqjchcan
nostdress | <nil> DBG got lnurl request domain=zapaddress.com username=fishcake
nostdress | <nil> DBG Timed out NIP57 wait for payment=9ecaaac47b4650bfccab61560fd31c2f33782fed45cb5b8b466d17e310ff02b6
nostdress | <nil> DBG Timed out NIP57 wait for payment=bd778a78751921c1d4e9f4f1f55c72337ee2b6f9af4e700105e1738e45008b44
nostdress | <nil> DBG Timed out NIP57 wait for payment=8f3cdf7258a50100326d95928bb14d0f5cfef576cd85109dfa97e5dcd0b00d64
nostdress | <nil> DBG Timed out NIP57 wait for payment=0c74f2f1a8646167c18f9a292cd513cccc158bb35cb3ccb4d7c5d59eed02c0a7
nostdress | <nil> DBG Timed out NIP57 wait for payment=2d64b0f384178e72170182fc6fa94913f7e71f0193200ee0ae2fbf692bd7b03b

**Comment by benthecarman** [comment]
what is your npub, maybe i accidentally deleted the wrong one

**Comment by A18N15** [comment]
Hi Ben,

Here it is:

npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve

Thank you

**Comment by benthecarman** [comment]
Yeah looks like i accidenitally deleted one configured for the zapple pay account lol, yours is now deleted

**Comment by A18N15** [comment]
lol thanks again ben!
